---
title: "Смета расходов с 01.11.2024"
format: html
editor: source
---

::: {.panel-tabset}

### график

```{r}
#| echo: false
#| message: false

library(tidyverse)
library(plotly)

df <- readxl::read_xlsx("smeta_01.11.2024.xlsx")

df |> 
  group_by(level_1) |> 
  summarise(value = sum(amount)) |> 
  mutate(parents = "") |> 
  rename(labels = level_1) ->
  l1

df |> 
  group_by(level_2, level_1) |> 
  summarise(value = sum(amount)) |>
  rename(parents = level_1,
         labels = level_2) |> 
  na.omit() ->
  l2

df |> 
  group_by(level_3, level_2) |> 
  summarise(value = sum(amount)) |>
  rename(parents = level_2,
         labels = level_3) |> 
  na.omit() ->
  l3

df |> 
  group_by(level_4, level_3) |> 
  summarise(value = sum(amount)) |>
  rename(parents = level_3,
         labels = level_4) |> 
  na.omit() ->
  l4

l1 |> 
  bind_rows(l2, l3, l4) |> 
  select(parents, labels, value)  ->
  all_merged

plot_ly(
  type='treemap',
  labels=all_merged$labels,
  parents=all_merged$parents,
  values=all_merged$value)
```

### таблица

```{r}
#| echo: false
#| message: false

df |> 
  DT::datatable(class = 'cell-border stripe', 
                rownames = FALSE, 
                filter = 'top', 
                options = list(pageLength = 20, 
                               autoWidth = TRUE, 
                               info = FALSE,
                               dom = 'fBltp',
                               paginate = TRUE))
```

:::

Составлено на основе официальной сметы, представленной УК ([скачать](https://raw.githubusercontent.com/agricolamz/2024.09.22_treemap/refs/heads/main/smeta_01.11.2024.pdf)).

Данные в формате `.xlsx` доступны по ссылке ([скачать](https://raw.githubusercontent.com/agricolamz/2024.09.22_treemap/refs/heads/main/smeta_01.11.2024.xlsx)).
